name: Snake Game

on:
  schedule:
    - cron: '0 0 * * *' # Schedule it to run daily

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: dennisomari 
          outputs: |
            dist/github-snake.svg
